# Generated by Django 4.0.2 on 2022-02-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allsite',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='Id', editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('type', models.CharField(choices=[('地方政府', '地方政府'), ('国家部委', '国家部委'), ('拟在建项目', '拟在建项目'), ('设备企业', '设备企业'), ('矿山企业', '矿山企业'), ('设计研究院', '设计研究院'), ('新闻媒体', '新闻媒体')], db_column='Type', max_length=255, verbose_name='类型')),
                ('province', models.CharField(db_column='Province', max_length=255, verbose_name='省')),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True, verbose_name='市')),
                ('countrytown', models.CharField(blank=True, db_column='CountryTown', max_length=255, null=True, verbose_name='县')),
                ('urlname', models.CharField(blank=True, db_column='Urlname', max_length=255, null=True, verbose_name='网站名')),
                ('url', models.TextField(unique=True, verbose_name='网址')),
                ('urlpath', models.CharField(blank=True, db_column='UrlPath', max_length=255, null=True, verbose_name='网站目录')),
                ('status', models.CharField(choices=[('成功', '成功'), ('未成功', '未成功'), ('未做', '未做'), ('无网址', '无网址'), ('网址错误', '网址错误'), ('其他', '其他')], db_column='Status', default='未做', max_length=255, verbose_name='状态')),
                ('manager', models.CharField(blank=True, choices=[('梁子晨', '梁子晨'), ('祁广俊', '祁广俊'), ('娄程豪', '娄程豪'), ('于婷婷', '于婷婷'), ('刘效良', '刘效良'), ('-', '-')], db_column='Manager', max_length=255, null=True, verbose_name='管理员')),
                ('classifyps', models.CharField(blank=True, db_column='ClassifyPs', max_length=255, null=True, verbose_name='分类补充')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('doubletype', models.CharField(blank=True, choices=[('通用爬取', '通用爬取'), ('不适合单页', '不适合单页'), ('单页抓取', '单页抓取'), ('困难网站', '困难网站'), ('娄程豪', '娄程豪'), ('爬虫二期', '爬虫二期'), ('祁广俊', '祁广俊'), ('四大省', '四大省'), ('无网址', '无网址'), ('仅首页', '仅首页')], db_column='DoubleType', max_length=255, null=True, verbose_name='二次类别筛选')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '目标网站',
                'verbose_name_plural': '目标网站',
                'db_table': 'AllSite',
                'managed': False,
            },
        ),
    ]
